### ISSUE TITLE
Compiler errors.

### ISSUE THREAD

**Issue by fluxa** [aljvilla/hn-feed-test#1]
Hi, could you please take a look at this error. I followed the instructions on the Read.me but still can't open the app. Thanks.

![image](https://user-images.githubusercontent.com/208245/46763483-552b1f80-ccb0-11e8-931a-b4349ee38990.png)

**Comment by aljvilla** [comment]
la ruta correcta es http://localhost:8000 not http://localhost:8000/webpack-dev-server

**Comment by fluxa** [comment]
The main path (localhost:8000) gives me this:

![image](https://user-images.githubusercontent.com/208245/46814797-de456380-cd4f-11e8-8ac1-847f5eb32bdc.png)



The server is up and running according with the instructions on the readme:

![image](https://user-images.githubusercontent.com/208245/46814575-6d9e4700-cd4f-11e8-989b-c16d948eb941.png)

The front app doesn't seem to be calling API on the backend.
